1)

[0:19] brief:~% ./p/cdist/bin/cdist config -v localhost 
INFO: localhost: Running global explorers
INFO: localhost: Running initial manifest /home/users/nico/oeffentlich/rechner/projekte/cdist/conf/manifest
^Chandling in config
Traceback (most recent call last):
  File "/usr/lib/python3.2/functools.py", line 176, in wrapper
    result = cache[key]
KeyError: (<class 'str'>, '[ \\f\\t]*(\\\\\\r?\\n[ \\f\\t]*)*(#[^\\r\\n]*)?((([0-9]+[jJ]|(([0-9]+\\.[0-9]*|\\.[0-9]+)([eE][-+]?[0-9]+)?|[0-9]+[eE][-+]?[0-9]+)[jJ])|(([0-9]+\\.[0-9]*|\\.[0-9]+)([eE][-+]?[0-9]+)?|[0-9]+[eE][-+]?[0-9]+)|(0[xX][0-9a-fA-F]+|0[bB][01]+|0[oO][0-7]+|(?:0+|[1-9][0-9]*)))|((\\*\\*=?|>>=?|<<=?|!=|//=?|->|[+\\-*/%&|^=<>]=?|~)|[][(){}]|(\\r?\\n|\\.\\.\\.|[:;.,@]))|([bB]?[rR]?\'[^\\n\'\\\\]*(?:\\\\.[^\\n\'\\\\]*)*\'|[bB]?[rR]?"[^\\n"\\\\]*(?:\\\\.[^\\n"\\\\]*)*")|\\w+)', 32)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.2/site.py", line 58, in <module>
    import traceback
  File "/usr/lib/python3.2/traceback.py", line 3, in <module>
    import linecache
  File "/usr/lib/python3.2/linecache.py", line 10, in <module>
    import tokenize
  File "/usr/lib/python3.2/tokenize.py", line 118, in <module>
    _compile, (Token, PseudoToken, Single3, Double3))
  File "/usr/lib/python3.2/tokenize.py", line 115, in _compile
    return re.compile(expr, re.UNICODE)
  File "/usr/lib/python3.2/re.py", line 206, in compile
    return _compile(pattern, flags)
  File "/usr/lib/python3.2/re.py", line 255, in _compile
    return _compile_typed(type(pattern), pattern, flags)
  File "/usr/lib/python3.2/functools.py", line 180, in wrapper
    result = user_function(*args, **kwds)
  File "/usr/lib/python3.2/re.py", line 267, in _compile_typed
    return sre_compile.compile(pattern, flags)
  File "/usr/lib/python3.2/sre_compile.py", line 495, in compile
    code = _code(p, flags)
  File "/usr/lib/python3.2/sre_compile.py", line 477, in _code
    _compile_info(code, p, flags)                                                                        
  File "/usr/lib/python3.2/sre_compile.py", line 366, in _compile_info
[0:19] brief:~%     lo, hi = pattern.getwidth()
  File "/usr/lib/python3.2/sre_parse.py", line 163, in getwidth
    i, j = av[1].getwidth()
  File "/usr/lib/python3.2/sre_parse.py", line 153, in getwidth
    l, h = av.getwidth()
  File "/usr/lib/python3.2/sre_parse.py", line 163, in getwidth
    i, j = av[1].getwidth()
  File "/usr/lib/python3.2/sre_parse.py", line 153, in getwidth
    l, h = av.getwidth()
  File "/usr/lib/python3.2/sre_parse.py", line 163, in getwidth
    i, j = av[1].getwidth()
  File "/usr/lib/python3.2/sre_parse.py", line 153, in getwidth
    l, h = av.getwidth()
  File "/usr/lib/python3.2/sre_parse.py", line 163, in getwidth
    i, j = av[1].getwidth()
  File "/usr/lib/python3.2/sre_parse.py", line 153, in getwidth
    l, h = av.getwidth()
  File "/usr/lib/python3.2/sre_parse.py", line 163, in getwidth
    i, j = av[1].getwidth()
  File "/usr/lib/python3.2/sre_parse.py", line 148, in getwidth
    for op, av in self.data:
KeyboardInterrupt

2)
[0:19] brief:~% ./p/cdist/bin/cdist config -v localhost
INFO: localhost: Running global explorers
INFO: localhost: Running initial manifest /home/users/nico/oeffentlich/rechner/projekte/cdist/conf/manifest
^CFatal Python error: Py_Initialize: can't initialize sys standard streams
Traceback (most recent call last):
  File "/usr/lib/python3.2/io.py", line 60, in <module>
handling in config
    import _io
  File "/usr/lib/python3.2/os.py", line 26, in <module>
[0:19] brief:~%     import sys, errno
KeyboardInterrupt
/home/users/nico/oeffentlich/rechner/projekte/cdist/conf/manifest/init: line 6:  8370 Aborted                 __directory /tmp/foo/bar --parents yes --owner nico --group postdrop --recursive yes

[0:19] brief:~% 

3)

[1:12] brief:cdist% ./bin/cdist config -vp -c ~/p/cdist-nutzung ikq05.ethz.ch ikq06.ethz.ch ikq07.ethz.ch
INFO: ikq06.ethz.ch: Running global explorers
INFO: ikq05.ethz.ch: Running global explorers
INFO: ikq07.ethz.ch: Running global explorers
INFO: ikq07.ethz.ch: Running initial manifest /home/users/nico/p/cdist-nutzung/conf/manifest
INFO: ikq06.ethz.ch: Running initial manifest /home/users/nico/p/cdist-nutzung/conf/manifest
INFO: ikq05.ethz.ch: Running initial manifest /home/users/nico/p/cdist-nutzung/conf/manifest
INFO: ikq07.ethz.ch: Running object manifests and type explorers
INFO: ikq07.ethz.ch: Running manifest and explorers for __ethz_collectd/singleton
INFO: ikq05.ethz.ch: Running object manifests and type explorers
INFO: ikq05.ethz.ch: Running manifest and explorers for __ethz_collectd/singleton
^Ccatch, ikq05.ethz.ch
catch, ikq07.ethz.ch
[1:12] brief:cdist% ./bin/cdist config -vp -c ~/p/cdist-nutzung ikq05.ethz.ch ikq06.ethz.ch ikq07.ethz.ch
INFO: ikq05.ethz.ch: Running global explorers
INFO: ikq06.ethz.ch: Running global explorers
INFO: ikq07.ethz.ch: Running global explorers
INFO: ikq05.ethz.ch: Running initial manifest /home/users/nico/p/cdist-nutzung/conf/manifest
INFO: ikq06.ethz.ch: Running initial manifest /home/users/nico/p/cdist-nutzung/conf/manifest
INFO: ikq07.ethz.ch: Running initial manifest /home/users/nico/p/cdist-nutzung/conf/manifest
^CTraceback (most recent call last):
  File "/usr/lib/python3.2/site.py", line 529, in <module>
catch, ikq05.ethz.ch
Fatal Python error: Py_Initialize: can't initialize sys standard streams
Traceback (most recent call last):
  File "/usr/lib/python3.2/io.py", line 60, in <module>
catch, ikq07.ethz.ch
    main()
  File "/usr/lib/python3.2/site.py", line 517, in main
catch, ikq06.ethz.ch
    known_paths = addusersitepackages(known_paths)
  File "/usr/lib/python3.2/site.py", line 263, in addusersitepackages
Fatal Python error: Py_Initialize: can't initialize sys standard streams
Traceback (most recent call last):
  File "/usr/lib/python3.2/io.py", line 60, in <module>
    user_site = getusersitepackages()
  File "/usr/lib/python3.2/site.py", line 238, in getusersitepackages
    user_base = getuserbase() # this will also set USER_BASE
  File "/usr/lib/python3.2/site.py", line 228, in getuserbase
    USER_BASE = get_config_var('userbase')
  File "/usr/lib/python3.2/sysconfig.py", line 577, in get_config_var
    return get_config_vars().get(name)
  File "/usr/lib/python3.2/sysconfig.py", line 474, in get_config_vars
    _init_posix(_CONFIG_VARS)
  File "/usr/lib/python3.2/sysconfig.py", line 344, in _init_posix
    parse_config_h(f, vars)
  File "/usr/lib/python3.2/sysconfig.py", line 386, in parse_config_h
    line = fp.readline()
  File "/usr/lib/python3.2/codecs.py", line 302, in decode
    self.buffer = data[consumed:]
KeyboardInterrupt
    import _io
  File "/usr/lib/python3.2/os.py", line 49, in <module>
    import posixpath as path
  File "/usr/lib/python3.2/posixpath.py", line 11, in <module>
    import _io
  File "/usr/lib/python3.2/os.py", line 44, in <module>
    """    from posix import *
KeyboardInterrupt
/home/users/nico/p/cdist-nutzung/conf/manifest/init: line 10: 19830 Aborted                 __ethz_systems_root_via_ssh $ik --state present

KeyboardInterrupt
[1:12] brief:cdist% /home/users/nico/p/cdist-nutzung/conf/manifest/init: line 10: 19829 Aborted                 __ethz_systems_root_via_ssh $ik --state present


